### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jwillmer** [TigPT/cronjobs#1]
would you mind adding logging so that we can see that a cron job was triggered?

**Comment by tigpt** [comment]
Hi @jwillmer and thanks for the feedback.

You can set cron output to /dev/stdout and use "docker logs [container_name]" to see the logs, or send it to /var/logs and mount that folder to your disk in docker-composer file:
`- ./log:/var/log/`

Test a root file with this cronjob to see if it works, you should see the result of the cron request
`* * * * * curl -v https://tig.pt/test-cron > /dev/stdout`

Does this solutions work for you or you need other type of logs?
(I will add this info to the help to help others)

**Comment by jwillmer** [comment]
cool, yes, that works
