### ISSUE TITLE
User ID and group ID

### ISSUE THREAD

**Issue by jwillmer** [TigPT/cronjobs#2]
I have the problem that my file can't be read since my host has different user permissions. Could you add options to set the user and group ID via docker?

**Comment by tigpt** [comment]
What is the error that you get when you try to run it?

Does this help?
https://serverfault.com/questions/78159/what-could-cause-permission-denied-for-command-crontab-e

**Comment by jwillmer** [comment]
there is no error, the file just does not get used. `chown root:root` works without a problem but it is a manual step that i will forget especially because `cron` does not throw any visible arrows then it can't access the file.

**Comment by tigpt** [comment]
I’ve been digging into this and didn’t find a perfect solution for you that don’t impact others that may use this image.

Docker compose volumes are mounted after docker run, and don’t make sense for me to do the Cron file import in dockerfile.

I think the best way for you not to forget it is to create a simple bash file that run chown before docket-compose up -d and run that script to start the container.

Did you found any alternative way?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jwillmer** [comment]
I ended up forking your repo and adding the file in the build. now I rebuild the repo in the docker compose every time I change the file.

**Comment by tigpt** [comment]
Yap, that’s one of the options I came across, thanks for the feedback.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
